apiVersion: apps/v1
kind: Deployment
metadata:
  name: sibr-datablase
  labels:
    app: sibr-datablase
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sibr-datablase
  template:
    metadata:
      labels:
        app: sibr-datablase
    spec:
      containers:
        - name: sibr-datablase
          image: corvimae/datablase:{{IMAGE_VERSION}}
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: datablase-secrets
                  key: pgHost
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: datablase-secrets
                  key: pgPort
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: datablase-secrets
                  key: pgDatabase
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: datablase-secrets
                  key: pgUser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: datablase-secrets
                  key: pgPassword
            - name: SIBR_PRODUCTION
              value: '1'
